version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_CONNECTION_STRING: postgres://postgres:postgres@db/postgres
      LOG_FILE: "log.txt"
      KNOWN_CUSTOMERS: "known-customers.json"
      INPUT_DATA: '["transactions-1.json","transactions-2.json"]'
    volumes:
      - .:/usr/src/app
      - logs:/usr/src/app/logs
    command: >
      sh -c "chmod +x ./run_migrations.sh && 
            sleep 10 && 
            ./run_migrations.sh && 
            cargo run --release"

volumes:
  postgres_data:
  logs:
