[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
async-trait = "0.1"
rust_decimal = { version = "1.35.0", features = ["db-postgres"] }

models = { path = "../models" }
